version: '3'

tasks:
    # MARK: CLI Utils
    build:
        cmds:
            - xcrun xcodebuild -scheme All build -destination "name=My Mac" | xcbeautify

    app-test:
        cmds:
            - set -o pipefail && xcrun xcodebuild clean test -configuration Testing -scheme All -testPlan App | xcbeautify

    frameworks-test:
        cmds:
            - set -o pipefail && xcrun xcodebuild clean test -configuration Testing -scheme All -testPlan Frameworks | xcbeautify

    integration-test:
        cmds:
            - set -o pipefail && xcrun xcodebuild clean test -configuration Testing -scheme All -testPlan Integration | xcbeautify

    test:
        cmds:
            - set -o pipefail && xcrun xcodebuild clean test -configuration Testing -scheme All -testPlan All | xcbeautify

    format:
        - find ./Sources ./Tests \( -name '*.h' -o -name '*.m' -o -name '*.mm' -o -name '*.cpp' \) -print0 | xargs -0 clang-format -i
        - swiftformat .

    package:
        vars:
            PACKAGE_PATH: '{{.PRODUCT_PATH | default "AquaSKK.tar.bz2"}}'
        cmds:
            - task: build
              vars:
                ARCHIVE_PATH: AquaSKK.xcarchive
                PRODUCT_PATH: Products/AquaSKK/
            - cp README.md Products/AquaSKK/
            - cp Sources/Installer/install.sh Products/AquaSKK/
            - (cd Products/AquaSKK/; tar cvjf ../../{{.PACKAGE_PATH}} .)

    # MARK: CI
    ci-build:
        # TODO: Packaging
        cmds:
            - xcrun xcodebuild -scheme All build -destination "platform=macOS,arch=arm64" | xcbeautify --renderer github-actions

    ci-test:
        vars:
            TEST_RESULTS_BUNDLE: '{{.TEST_RESULTS_BUNDLE | default "TestResults.xcresult"}}'
        cmds:
            - rm -rf {{.TEST_RESULTS_BUNDLE}}
            - swiftformat --lint --verbose .
            - set -o pipefail &&
              xcrun xcodebuild clean test
                  -configuration Testing
                  -scheme All
                  -testPlan CI
                  -derivedDataPath ./DerivedData
                  -resultBundlePath {{.TEST_RESULTS_BUNDLE}} |
              tee xcodebuild.log |
              xcbeautify --renderer github-actions
