version: '3'

tasks:
    test:
        vars:
            TEST_RESULTS_BUNDLE: '{{.TEST_RESULTS_BUNDLE | default "TestResults.xcresult"}}'
        preconditions:
            - which xcpretty
        cmds:
            - rm -rf {{.TEST_RESULTS_BUNDLE}}
            - set -o pipefail &&
              xcrun xcodebuild test
                  -configuration Testing
                  -scheme All
                  -testPlan CI
                  -derivedDataPath ./DerivedData
                  -resultBundlePath {{.TEST_RESULTS_BUNDLE}} |
              tee xcodebuild.log |
              xcpretty -t

    lint:
        preconditions:
            - which swiftformat
        cmds:
            - swiftformat --lint --verbose .

    format:
        preconditions:
            - which swiftformat
        cmds:
            - find . -name '*.m' -or -name '*.mm' -or -name '*.cpp' -or -name '*.h' -print0 | xargs --null clang-format -i
            - swiftformat .
