name: Tests

on: [push, workflow_dispatch]

jobs:
    Tests:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Set current datetime as env variable
              run: echo "TEST_RESULTS_BUNDLE=$(date +'TestResults-%Y%m%d%H%M%S.xcresult')" >> $GITHUB_ENV
            - name: Run Check
              run: task lint test
            - name: Package xcresult
              if: success() || failure()
              run: zip -r ${{ env.TEST_RESULTS_BUNDLE }}.zip ${{ env.TEST_RESULTS_BUNDLE }}
            - name: Upload xcresult
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                  name: ${{ env.TEST_RESULTS_BUNDLE }}
                  path: ${{ env.TEST_RESULTS_BUNDLE }}.zip
                  compression-level: 1
            - name: Upload xcodebuild.log
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                  name: xcodebuild.log
                  path: xcodebuild.log
                  compression-level: 1
            - name: Upload Builds Logs
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                  name: BuildLogs
                  path: DerivedData/Logs/Build
                  compression-level: 1
    Builds:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - run: set -o pipefail && xcrun xcodebuild -scheme All build -destination "platform=macOS" | xcpretty
