name: Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftformat --lint .
      - run: xcrun xcodebuild -scheme All test
